### ISSUE TITLE
Support Model for Meta-Llama-3.1

### ISSUE THREAD

**Issue by jiangguochaoGG** [YaoJiayi/CacheBlend#13]
When I try to execute `example/blend_samsum.py` using the `Meta-Llama-3.1-8B-Instruct` model, the code gives the following error message:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "~/CacheBlend/example/blend_samsum.py", line 136, in <module>
[rank0]:     output = llm.generate([input_prompt], sampling_params)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/utils.py", line 1032, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 348, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 720, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1600, in step
[rank0]:     outputs = self.model_executor.execute_model(
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 130, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 327, in execute_model
[rank0]:     output = self.model_runner.execute_model(
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1543, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 527, in forward
[rank0]:     model_output = self.model(input_ids, positions, kv_caches,
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 400, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 275, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 201, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata, status, cache_fuse_metadata, old_kv)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/attention/layer.py", line 104, in forward
[rank0]:     return self.impl.forward(query,
[rank0]:   File "~/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/attention/backends/xformers.py", line 540, in forward
[rank0]:     temp_diff = torch.sum((value[:-last_len, ...] - value_old[:-last_len, ...])**2, dim=[1, 2])
[rank0]: RuntimeError: The size of tensor a (3009) must match the size of tensor b (3010) at non-singleton dimension 0
```

This phenomenon is very strange, because in vLLM, both Mistral and Llama use `llama.py` to load the model, and when I use `Mistral-7B-Instruct-v0.2` and `Mistral-7B-Instruct-v0.3`, everything is normal.

**Comment by jiangguochaoGG** [comment]
The error is caused by the token being misidentified by the tokenizer at the chunk connection.

**Comment by Parallel-Hao** [comment]
Hi @jiangguochaoGG, do you know how to fix this error?

**Comment by jiangguochaoGG** [comment]
> Hi @jiangguochaoGG, do you know how to fix this error?

In vLLM, use `prompt_token_ids` in `llm.generate()` for pre-compute and blend to keep the dimension between `value` and `value_old`.
